version: '3.10'
services:
  db:
    image: postgres:15
    env_file:
      - .env
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  bot:
    build: .
    command: sh -c "make migrate && python -m bot"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/aiogram-book-bot
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: on-failure


volumes:
  postgres_data:
  redis-data:
