version: "3.10"

services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/aiogram-book-bot
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
